[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
chaindepth = "3Ctc2FgnNHQtGAcZftMS4ykLhJYjLzBD3hELKy55DnKo"

[programs.devnet]
chaindepth = "3Ctc2FgnNHQtGAcZftMS4ykLhJYjLzBD3hELKy55DnKo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-devnet = "ts-node scripts/init-devnet.ts"
