[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vrf_poc = "2JDex7BacQRsCSx5c2svgCj6or5sEgq1QpWzDSQZ4mRp"

[programs.localnet]
vrf_poc = "2JDex7BacQRsCSx5c2svgCj6or5sEgq1QpWzDSQZ4mRp"

[provider]
cluster = "devnet"
wallet = "../devnet-wallet.json"

[scripts]
test = "npm run test:devnet"
